// react-app/src/TreeComponent.jsx
import React from 'react';
import './TreeComponent.css';

const colours = ['red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'];
let index = 0;
const nextColour = () => {
  const colour = colours[index];
  index++;
  if (index >= colours.length) {
    index = 0;
  }

  return colour;
}

function TreeComponentFlip({ node }) {
  const { drawKey, left, right } = node;
  const [flipped, setFlipped] = React.useState(true);
  const colour = React.useMemo(nextColour);

  console.log(`Evaluated ${drawKey}`);

  return (
    <div className={`tree ${colour}`}>
      <button onClick={() => {setFlipped(!flipped)}}>Update</button>
      <div className="nodes">
        { flipped
          ? <>
            { left && <TreeComponentFlip node={left} /> }
            { right && <TreeComponentFlip node={right} /> }
          </>
          : <>
            { right && <TreeComponentFlip node={right} /> }
            { left && <TreeComponentFlip node={left} /> }
          </>
        }
      </div>
    </div>
  );
}

function TreeComponentColour({ node }) {
  const { drawKey, left, right } = node;
  const [colour, setColour] = React.useState(nextColour);

  console.log(`Evaluated ${drawKey}`);

  return (
    <div className={`tree ${colour}`}>
      <button onClick={() => {setColour(nextColour())}}>Update</button>
      <div className="nodes">
        { left && <TreeComponentColour node={left} /> }
        { right && <TreeComponentColour node={right} /> }
      </div>
    </div>
  );
}

function TreeComponent({ node }) {
  const { drawKey, left, right } = node;
  const [state, setState] = React.useState(true);

  console.log(`Evaluated ${drawKey}`);

  return (
    <div className={`tree ${nextColour()}`}>
      <button onClick={() => {setState(!state)}}>Update</button>
      <div className="nodes">
        { left && <TreeComponent node={left} /> }
        { right && <TreeComponent node={right} /> }
      </div>
    </div>
  );
}

export default TreeComponentColour;

// svelte-app/src/TreeComponent.svelte
<script>
  import nextColour from "./nextColour";
  let colour = nextColour();

  function handleClick() {
    colour = nextColour();
  }

  export let node;
</script>

<div class={`tree ${colour}`}>
  <button on:click={handleClick}>Update</button>
  <div class="nodes">
    {#if node.left}
      <svelte:self node={node.left} />
    {/if}
    {#if node.right}
      <svelte:self node={node.right} />
    {/if}
  </div>
</div>

<style>
  button {
    margin: 25px 0;
    padding: 10px;
  }

  .tree {
    text-align: center;
    width: auto;
  }

  .nodes {
    display: flex;
  }

  .red {
    background-color: red;
  }
  .orange {
    background-color: orange;
  }
  .yellow {
    background-color: yellow;
  }
  .green {
    background-color: green;
  }
  .blue {
    background-color: blue;
  }
  .indigo {
    background-color: indigo;
  }
  .violet {
    background-color: violet;
  }
</style>
